# Build Spec for AWS CodeBuild CI

version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y curl gnupg2 python3-pip
      - pip3 install future psutil torch==1.5.0

  build:
    commands:
      - nvidia-smi
      - python3 -m torch.utils.collect_env
